import { useEffect, useState } from 'react'
import { Modal, Form, Input, Switch, Button, Space, Select, Alert } from 'antd'
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons'
import type { FormLayoutItem, FormLayoutItemOption } from './types'
import type { FormLayoutItemDataSource } from './types'
import { DEPARTMENTS, USER_GROUPS } from './formOptionsData'

const TYPE_WITH_OPTIONS = ['选择列表', 'radio', 'checkbox', '多选']
const TYPE_REFERENCE = ['reference', 'lookup', 'person', 'department', 'usergroup']
const TYPE_WITH_PLACEHOLDER = ['singleline', 'string', 'multiline', '多行文本', 'counter', 'integer', 'datetime', '日期', 'reference', 'lookup', 'cascader', '级联']

function isAutoGeneratedField(item: FormLayoutItem): boolean {
  return item.autoGenerated === true || item.technicalName === 'sys_id' || item.label === '唯一编码'
}

function isReferenceType(item: FormLayoutItem): boolean {
  const t = (item.type || '').toLowerCase()
  return TYPE_REFERENCE.some((k) => t === k.toLowerCase()) || item.type === 'Reference' || item.type === '人员' || item.type === '部门'
}

export interface FormItemEditModalProps {
  open: boolean
  item: FormLayoutItem | null
  groupKey: string
  onClose: () => void
  onSave: (updated: FormLayoutItem) => void
}

export default function FormItemEditModal({ open, item, groupKey, onClose, onSave }: FormItemEditModalProps) {
  const [form] = Form.useForm()
  const [options, setOptions] = useState<FormLayoutItemOption[]>([])
  const [dataSource, setDataSource] = useState<FormLayoutItemDataSource>('all')
  const [dataSourceDepartmentId, setDataSourceDepartmentId] = useState<string | undefined>()
  const [dataSourceGroupId, setDataSourceGroupId] = useState<string | undefined>()
  const [multiple, setMultiple] = useState(false)

  const isAudit = groupKey === 'audit'
  const rawType = (item?.type ?? 'string').toLowerCase()
  const isAutoGen = item ? isAutoGeneratedField(item) : false
  const isRef = item ? isReferenceType(item) : false
  const hasManualOptions = item && TYPE_WITH_OPTIONS.some((t) => rawType === t.toLowerCase() || item.type === t)
  const hasPlaceholder = item && !isAutoGen && TYPE_WITH_PLACEHOLDER.some((t) => rawType === t.toLowerCase() || item.type === t)
  const isTextarea = rawType === 'multiline' || item?.type === '多行文本'

  useEffect(() => {
    if (!open || !item) return
    form.setFieldsValue({
      label: item.label,
      required: item.required,
      readOnly: item.readOnly ?? isAudit,
      placeholder: item.placeholder,
      textareaRows: item.textareaRows ?? 3,
    })
    setOptions(item.options && item.options.length > 0 ? [...item.options] : [{ value: '', label: '' }])
    setDataSource(item.dataSource ?? 'all')
    setDataSourceDepartmentId(item.dataSourceFilter?.departmentId)
    setDataSourceGroupId(item.dataSourceFilter?.groupId)
    setMultiple(item.multiple ?? false)
  }, [open, item, isAudit, form])

  const handleOk = () => {
    if (!item) return
    if (isAutoGen) {
      form.validateFields(['label']).then((values) => {
        onSave({ ...item, label: values.label })
        onClose()
      })
      return
    }
    form.validateFields().then((values) => {
      const optList = options.filter((o) => o.value !== '' || o.label !== '')
      const next: FormLayoutItem = {
        ...item,
        label: values.label,
        required: values.required,
        readOnly: isAudit ? true : values.readOnly,
        placeholder: values.placeholder || undefined,
        textareaRows: Number(values.textareaRows) || 3,
        options: optList.length > 0 ? optList : undefined,
        dataSource: isRef ? dataSource : undefined,
        dataSourceFilter:
          isRef && (dataSource === 'by_department' || dataSource === 'by_group')
            ? { departmentId: dataSource === 'by_department' ? dataSourceDepartmentId : undefined, groupId: dataSource === 'by_group' ? dataSourceGroupId : undefined }
            : undefined,
        multiple: isRef ? multiple : undefined,
      }
      onSave(next)
      onClose()
    })
  }

  const addOption = () => setOptions((prev) => [...prev, { value: '', label: '' }])
  const removeOption = (index: number) => setOptions((prev) => prev.filter((_, i) => i !== index))
  const changeOption = (index: number, field: 'value' | 'label', v: string) => {
    setOptions((prev) => prev.map((o, i) => (i === index ? { ...o, [field]: v } : o)))
  }

  if (!item) return null

  return (
    <Modal
      title="编辑表单项"
      open={open}
      onCancel={onClose}
      onOk={handleOk}
      width={560}
      destroyOnClose
      footer={[
        <Button key="cancel" onClick={onClose}>取消</Button>,
        <Button key="ok" type="primary" onClick={handleOk}>确定</Button>,
      ]}
    >
      {isAutoGen ? (
        <>
          <Form form={form} layout="vertical">
            <Form.Item name="label" label="显示标签" rules={[{ required: true, message: '请输入显示标签' }]}>
              <Input placeholder="如：唯一编码" />
            </Form.Item>
          </Form>
          <Alert
            type="info"
            showIcon
            message="自动生成字段"
            description="此字段根据识别规则自动生成，无需用户输入。生成规则、前缀及属性映射请在配置类「识别规则」步骤中配置。"
            style={{ marginTop: 12 }}
          />
        </>
      ) : (
        <Form form={form} layout="vertical" initialValues={{ required: false, readOnly: false }}>
          <Form.Item name="label" label="显示标签" rules={[{ required: true, message: '请输入显示标签' }]}>
            <Input placeholder="如：名称" />
          </Form.Item>
          <Form.Item name="required" label="必填" valuePropName="checked">
            <Switch />
          </Form.Item>
          {!isAudit && (
            <Form.Item name="readOnly" label="只读" valuePropName="checked">
              <Switch />
            </Form.Item>
          )}
          {hasPlaceholder && (
            <Form.Item name="placeholder" label="占位提示">
              <Input placeholder="如：请输入、请选择" />
            </Form.Item>
          )}
          {isTextarea && (
            <Form.Item name="textareaRows" label="多行行数">
              <Input type="number" min={1} max={20} />
            </Form.Item>
          )}

          {isRef && (
            <>
              <div style={{ marginBottom: 16 }}>
                <div style={{ marginBottom: 4, fontWeight: 500 }}>允许多选</div>
                <Switch checked={multiple} onChange={setMultiple} />
                <span style={{ marginLeft: 8, fontSize: 12, color: '#8c8c8c' }}>开启后可选择多个人员/部门/用户组</span>
              </div>
              <Form.Item label="数据来源">
                <Select
                  value={dataSource}
                  onChange={(v) => setDataSource(v)}
                  options={[
                    { value: 'all', label: '全部内部人员/部门/用户组' },
                    { value: 'by_department', label: '按部门筛选（仅该部门人员）' },
                    { value: 'by_group', label: '按用户组筛选' },
                    { value: 'manual', label: '手动指定选项列表' },
                  ]}
                  style={{ width: '100%' }}
                />
              </Form.Item>
              {dataSource === 'by_department' && (
                <Form.Item label="筛选部门">
                  <Select
                    value={dataSourceDepartmentId}
                    onChange={setDataSourceDepartmentId}
                    allowClear
                    placeholder="选择部门后，人员列表仅显示该部门成员"
                    options={DEPARTMENTS.map((d) => ({ value: d.id, label: d.name }))}
                    style={{ width: '100%' }}
                  />
                </Form.Item>
              )}
              {dataSource === 'by_group' && (
                <Form.Item label="筛选用户组">
                  <Select
                    value={dataSourceGroupId}
                    onChange={setDataSourceGroupId}
                    allowClear
                    placeholder="选择用户组"
                    options={USER_GROUPS.map((g) => ({ value: g.id, label: g.name }))}
                    style={{ width: '100%' }}
                  />
                </Form.Item>
              )}
              {dataSource === 'manual' && (
                <Form.Item label="选项列表（手动维护）">
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {options.map((opt, index) => (
                      <Space key={index} style={{ width: '100%' }} align="center">
                        <Input placeholder="值" value={opt.value} onChange={(e) => changeOption(index, 'value', e.target.value)} style={{ width: 120 }} />
                        <Input placeholder="显示文本" value={opt.label} onChange={(e) => changeOption(index, 'label', e.target.value)} style={{ flex: 1 }} />
                        <Button type="text" danger size="small" icon={<DeleteOutlined />} onClick={() => removeOption(index)} />
                      </Space>
                    ))}
                    <Button type="dashed" size="small" icon={<PlusOutlined />} onClick={addOption}>添加选项</Button>
                  </div>
                </Form.Item>
              )}
            </>
          )}

          {hasManualOptions && !isRef && (
            <Form.Item label="选项列表（下拉/单选/多选，手动维护）">
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {options.map((opt, index) => (
                  <Space key={index} style={{ width: '100%' }} align="center">
                    <Input placeholder="值" value={opt.value} onChange={(e) => changeOption(index, 'value', e.target.value)} style={{ width: 120 }} />
                    <Input placeholder="显示文本" value={opt.label} onChange={(e) => changeOption(index, 'label', e.target.value)} style={{ flex: 1 }} />
                    <Button type="text" danger size="small" icon={<DeleteOutlined />} onClick={() => removeOption(index)} />
                  </Space>
                ))}
                <Button type="dashed" size="small" icon={<PlusOutlined />} onClick={addOption}>添加选项</Button>
              </div>
            </Form.Item>
          )}
        </Form>
      )}
    </Modal>
  )
}
