import { Input, InputNumber, DatePicker, Select, Radio, Checkbox, Cascader } from 'antd'
import type { FormLayoutItem } from './types'
import { getPersonOptions, getDepartmentOptions, getUserGroupOptions, getCompanyOptions, getLocationOptions } from './formOptionsData'

const { TextArea } = Input

/** 唯一编码、sys_id 等根据识别规则自动生成，不提供输入 */
function isAutoGeneratedField(item: FormLayoutItem): boolean {
  return item.autoGenerated === true || item.technicalName === 'sys_id' || item.label === '唯一编码'
}

/** 根据字段/字段类型渲染对应表单控件，左侧标签、右侧控件，业务逻辑完整 */
export function renderFormControl(item: FormLayoutItem, readOnly?: boolean) {
  const disabled = readOnly ?? item.readOnly

  if (isAutoGeneratedField(item)) {
    return (
      <div style={{ padding: '8px 12px', background: '#f5f5f5', borderRadius: 4, color: '#8c8c8c', fontSize: 13 }}>
        根据识别规则自动生成，无需填写。请在「识别规则」中配置生成规则与前缀。
      </div>
    )
  }

  const rawType = item.type || 'string'
  const type = typeof rawType === 'string' ? rawType.toLowerCase() : 'string'

  const ph = item.placeholder ?? '请输入'
  const phSelect = item.placeholder ?? '请选择'
  const defaultRadioOptions = [
    { value: 'A', label: '选项 A' },
    { value: 'B', label: '选项 B' },
    { value: 'C', label: '选项 C' },
  ]
  const radioOptions = (item.options && item.options.length > 0 ? item.options : defaultRadioOptions) as { value: string; label: string }[]
  const textareaRows = item.textareaRows ?? 3

  /** 人员/部门/用户组/公司/位置：手动指定则用 options；否则按类型用内部数据 */
  const getReferenceOptions = (): { value: string; label: string }[] => {
    if (item.dataSource === 'manual' && item.options && item.options.length > 0) return item.options
    if (type === 'department' || item.technicalName === 'department') return getDepartmentOptions()
    if (item.technicalName === 'company') return getCompanyOptions()
    if (item.technicalName === 'location') return getLocationOptions()
    if (type === 'usergroup' || item.technicalName === 'supported_by' || item.technicalName === 'assignment_group') return getUserGroupOptions()
    return getPersonOptions(item.dataSourceFilter)
  }
  const selectOptions = getReferenceOptions()

  switch (type) {
    case 'singleline':
    case 'string':
      return <Input placeholder={ph} disabled={disabled} style={{ maxWidth: 400 }} />
    case 'multiline':
    case '多行文本':
      return <TextArea rows={textareaRows} placeholder={ph} disabled={disabled} style={{ maxWidth: 400 }} />
    case 'counter':
    case 'integer':
      return <InputNumber placeholder={ph} disabled={disabled} style={{ width: '100%', maxWidth: 400 }} min={0} />
    case 'datetime':
      return <DatePicker showTime style={{ width: '100%', maxWidth: 400 }} disabled={disabled} placeholder={phSelect} />
    case '日期':
      return <DatePicker style={{ width: '100%', maxWidth: 400 }} disabled={disabled} placeholder={phSelect} />
    case 'reference':
    case 'lookup':
    case 'person':
    case 'department':
    case 'usergroup':
      return (
        <Select
          mode={item.multiple ? 'multiple' : undefined}
          allowClear
          showSearch
          placeholder={item.multiple ? '请选择（可多选）' : phSelect}
          disabled={disabled}
          style={{ width: '100%', maxWidth: 400 }}
          options={selectOptions}
          filterOption={(input, option) => (option?.label ?? '').toString().toLowerCase().includes(input.toLowerCase())}
          maxTagCount={item.multiple ? 'responsive' : undefined}
        />
      )
    case '选择列表':
    case 'radio':
      return <Radio.Group disabled={disabled} options={radioOptions} />
    case 'checkbox':
    case '多选':
      return <Checkbox.Group disabled={disabled} options={radioOptions} />
    case 'cascader':
    case '级联':
      return (
        <Cascader
          disabled={disabled}
          placeholder={phSelect}
          style={{ width: '100%', maxWidth: 400 }}
          options={[
            { value: 'zhejiang', label: '浙江', children: [{ value: 'hangzhou', label: '杭州' }, { value: 'ningbo', label: '宁波' }] },
            { value: 'jiangsu', label: '江苏', children: [{ value: 'nanjing', label: '南京' }, { value: 'suzhou', label: '苏州' }] },
          ]}
        />
      )
    case 'table':
      return <div style={{ padding: '8px 12px', background: '#fafafa', borderRadius: 4, color: '#8c8c8c', fontSize: 13 }}>表格（子表）</div>
    case 'group':
      return <div style={{ padding: '4px 0', color: '#8c8c8c', fontSize: 12 }}>分组标题</div>
    default:
      return <Input placeholder="请输入" disabled={disabled} style={{ maxWidth: 400 }} />
  }
}
