import { useCallback, useState } from 'react'
import { Button, Form, Space } from 'antd'
import { CloseOutlined, EditOutlined, HolderOutlined, DownOutlined, RightOutlined } from '@ant-design/icons'
import type { FormLayoutItem } from './types'
import { FORM_GROUP_SCHEMA } from './types'
import { renderFormControl } from './FormFieldControl'
import FormItemEditModal from './FormItemEditModal'

export interface FormDesignCanvasFormProps {
  labelAlign?: 'left' | 'right' | 'top'
  labelWidth?: number
  formSize?: string
  labelSuffix?: string
  emptyText?: string
  /** 每行显示列数：1 / 2 / 3 */
  layoutColumns?: 1 | 2 | 3
}

interface FormDesignCanvasProps {
  items: FormLayoutItem[]
  onItemsChange: (items: FormLayoutItem[]) => void
  onSave?: () => void
  className?: string
  formProps?: FormDesignCanvasFormProps
}

const defaultFormProps: FormDesignCanvasFormProps = {
  labelAlign: 'left',
  labelWidth: 0,
  formSize: 'small',
  labelSuffix: '：',
  emptyText: '暂无数据',
  layoutColumns: 1,
}

export default function FormDesignCanvas({
  items,
  onItemsChange,
  onSave,
  className,
  formProps: formPropsIn,
}: FormDesignCanvasProps) {
  const formProps = { ...defaultFormProps, ...formPropsIn }
  const columns = formProps.layoutColumns ?? 1

  const [groupExpanded, setGroupExpanded] = useState<Record<string, boolean>>(() =>
    FORM_GROUP_SCHEMA.reduce((acc, g) => ({ ...acc, [g.key]: true }), {} as Record<string, boolean>)
  )
  const [editingItem, setEditingItem] = useState<FormLayoutItem | null>(null)
  const [editingGroupKey, setEditingGroupKey] = useState<string>('')
  const [hoveredItemId, setHoveredItemId] = useState<string | null>(null)

  const toggleGroup = useCallback((key: string) => {
    setGroupExpanded((prev) => ({ ...prev, [key]: !prev[key] }))
  }, [])

  const handleDragEnter = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    e.dataTransfer.dropEffect = 'copy'
    const zone = e.currentTarget.closest('[data-drop-zone]') as HTMLElement
    if (zone) zone.classList.add('drop-zone-active')
  }, [])

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    e.dataTransfer.dropEffect = 'copy'
    const zone = e.currentTarget.closest('[data-drop-zone]') as HTMLElement
    if (zone) zone.classList.add('drop-zone-active')
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    const zone = e.currentTarget.closest('[data-drop-zone]') as HTMLElement
    if (zone && !zone.contains(e.relatedTarget as Node)) zone.classList.remove('drop-zone-active')
  }, [])

  const handleDrop = useCallback(
    (e: React.DragEvent, groupKey: string) => {
      e.preventDefault()
      e.stopPropagation()
      const zone = e.currentTarget.closest('[data-drop-zone]') as HTMLElement
      if (zone) zone.classList.remove('drop-zone-active')
      try {
        const raw = e.dataTransfer.getData('application/json') || e.dataTransfer.getData('text/plain')
        if (!raw) return
        const data = JSON.parse(raw) as
          | { type: 'field'; fieldName: string; fieldType?: string; technicalName?: string; required?: boolean }
          | { type: 'fieldType'; key: string; label: string }
        const id = `fd-${Date.now()}-${Math.random().toString(36).slice(2)}`
        const isAudit = groupKey === 'audit'
        if (data.type === 'field') {
          onItemsChange([
            ...items,
            {
              id,
              label: data.fieldName,
              type: data.fieldType || 'string',
              group: groupKey,
              technicalName: data.technicalName,
              required: data.required,
              readOnly: isAudit,
              autoGenerated: data.technicalName === 'sys_id',
            },
          ])
        } else {
          onItemsChange([
            ...items,
            { id, label: data.label, type: data.key, group: groupKey, readOnly: isAudit },
          ])
        }
        setGroupExpanded((prev) => ({ ...prev, [groupKey]: true }))
      } catch {
        // ignore
      }
    },
    [items, onItemsChange]
  )

  const removeItem = useCallback(
    (id: string) => {
      onItemsChange(items.filter((i) => i.id !== id))
    },
    [items, onItemsChange]
  )

  const handleEditSave = useCallback(
    (updated: FormLayoutItem) => {
      onItemsChange(items.map((i) => (i.id === updated.id ? updated : i)))
      setEditingItem(null)
      setEditingGroupKey('')
    },
    [items, onItemsChange]
  )

  const labelCol = columns === 1 ? { span: 6 } : { span: 24 }
  const wrapperCol = columns === 1 ? { span: 18 } : { span: 24 }

  return (
    <div className={className}>
      <p style={{ color: '#666', marginBottom: 12, fontSize: 13 }}>
        从右侧拖拽「字段」或「字段类型」到下方分组；分组标题可展开/折叠；表单项悬停可编辑或删除。
      </p>
      <Form
        key={items.map((i) => i.id).join(',')}
        layout={formProps.labelAlign === 'top' ? 'vertical' : 'horizontal'}
        labelCol={formProps.labelAlign === 'top' ? undefined : labelCol}
        wrapperCol={formProps.labelAlign === 'top' ? undefined : wrapperCol}
        labelAlign={formProps.labelAlign === 'right' ? 'right' : 'left'}
        colon
        size={formProps.formSize as 'small' | 'middle' | 'large' | undefined}
      >
        {FORM_GROUP_SCHEMA.map((g) => {
          const groupItems = items.filter((i) => i.group === g.key)
          const expanded = groupExpanded[g.key] !== false

          return (
            <div
              key={g.key}
              data-drop-zone
              onDragEnter={handleDragEnter}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={(e) => handleDrop(e, g.key)}
              style={{
                marginBottom: 16,
                minHeight: 52,
                padding: 16,
                background: '#fafafa',
                border: '1px dashed #d9d9d9',
                borderRadius: 8,
                transition: 'border-color .2s, background .2s',
              }}
              className="form-drop-zone"
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  cursor: 'pointer',
                  userSelect: 'none',
                  marginBottom: expanded ? 8 : 0,
                }}
                onClick={() => toggleGroup(g.key)}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  {expanded ? (
                    <DownOutlined style={{ fontSize: 12, color: '#8c8c8c' }} />
                  ) : (
                    <RightOutlined style={{ fontSize: 12, color: '#8c8c8c' }} />
                  )}
                  <span style={{ fontWeight: 600, color: '#262626' }}>{g.title}</span>
                  <span style={{ fontSize: 12, color: '#8c8c8c', fontWeight: 400 }}>（{groupItems.length} 项）</span>
                </div>
              </div>
              {expanded && (
                <>
                  <div style={{ fontSize: 12, color: '#8c8c8c', marginBottom: 12 }}>{g.subtitle}</div>
                  <div
                    style={{
                      display: 'flex',
                      flexDirection: 'column',
                      gap: 0,
                      minHeight: 36,
                    }}
                    onDragEnter={handleDragEnter}
                    onDragOver={handleDragOver}
                    onDragLeave={handleDragLeave}
                    onDrop={(e) => handleDrop(e, g.key)}
                  >
                    {groupItems.length === 0 ? (
                      <div style={{ color: '#bfbfbf', fontSize: 13, padding: '12px 0' }}>拖拽字段或字段类型到此处</div>
                    ) : columns === 1 ? (
                      groupItems.map((item, idx) => (
                        <FormCanvasRow
                          key={item.id}
                          item={item}
                          groupKey={g.key}
                          isLast={idx === groupItems.length - 1}
                          showActions={hoveredItemId === item.id}
                          onMouseEnter={() => setHoveredItemId(item.id)}
                          onMouseLeave={() => setHoveredItemId(null)}
                          onEdit={() => { setEditingItem(item); setEditingGroupKey(g.key) }}
                          onRemove={() => removeItem(item.id)}
                          renderControl={() => renderFormControl(item, g.key === 'audit')}
                          required={item.required}
                          label={item.label}
                        />
                      ))
                    ) : (
                      (() => {
                        const rows: FormLayoutItem[][] = []
                        for (let i = 0; i < groupItems.length; i += columns) {
                          rows.push(groupItems.slice(i, i + columns))
                        }
                        return rows.map((row, rowIdx) => (
                          <div
                            key={row.map((r) => r.id).join('-')}
                            style={{
                              display: 'grid',
                              gridTemplateColumns: `repeat(${columns}, 1fr)`,
                              gap: 16,
                              marginBottom: 16,
                              paddingBottom: 16,
                              borderBottom: rowIdx < rows.length - 1 ? '1px solid #f0f0f0' : 'none',
                            }}
                          >
                            {row.map((item) => (
                              <FormCanvasRow
                                key={item.id}
                                item={item}
                                groupKey={g.key}
                                isLast={false}
                                showActions={hoveredItemId === item.id}
                                onMouseEnter={() => setHoveredItemId(item.id)}
                                onMouseLeave={() => setHoveredItemId(null)}
                                onEdit={() => { setEditingItem(item); setEditingGroupKey(g.key) }}
                                onRemove={() => removeItem(item.id)}
                                renderControl={() => renderFormControl(item, g.key === 'audit')}
                                required={item.required}
                                label={item.label}
                                compact
                              />
                            ))}
                          </div>
                        ))
                      })()
                    )}
                  </div>
                </>
              )}
            </div>
          )
        })}
      </Form>
      {items.length > 0 && (
        <Space style={{ marginTop: 16 }}>
          <Button type="primary" size="small" onClick={() => onSave?.()}>
            保存表单布局
          </Button>
        </Space>
      )}

      <FormItemEditModal
        open={!!editingItem}
        item={editingItem}
        groupKey={editingGroupKey}
        onClose={() => { setEditingItem(null); setEditingGroupKey('') }}
        onSave={handleEditSave}
      />
    </div>
  )
}

function FormCanvasRow({
  item,
  isLast,
  showActions,
  onMouseEnter,
  onMouseLeave,
  onEdit,
  onRemove,
  renderControl,
  required,
  label,
  compact,
}: {
  item: FormLayoutItem
  groupKey: string
  isLast: boolean
  showActions: boolean
  onMouseEnter: () => void
  onMouseLeave: () => void
  onEdit: () => void
  onRemove: () => void
  renderControl: () => React.ReactNode
  required?: boolean
  label: string
  compact?: boolean
}) {
  return (
    <div
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: 8,
        marginBottom: compact ? 0 : isLast ? 0 : 16,
        paddingBottom: compact ? 0 : isLast ? 0 : 16,
        borderBottom: compact ? 'none' : isLast ? 'none' : '1px solid #f0f0f0',
      }}
    >
      <HolderOutlined style={{ color: '#bfbfbf', cursor: 'grab', marginTop: 8, flexShrink: 0 }} />
      <Form.Item
        name={item.technicalName || item.id}
        label={item.label}
        required={required}
        style={{ marginBottom: 0, flex: 1, minWidth: 0 }}
        rules={required ? [{ required: true, message: `请输入${label}` }] : undefined}
      >
        {renderControl()}
      </Form.Item>
      <div
        style={{
          display: 'flex',
          gap: 0,
          marginTop: 4,
          opacity: showActions ? 1 : 0,
          transition: 'opacity .15s',
          flexShrink: 0,
        }}
      >
        <Button type="text" size="small" icon={<EditOutlined />} onClick={onEdit} title="编辑" />
        <Button type="text" size="small" danger icon={<CloseOutlined />} onClick={onRemove} title="删除" />
      </div>
    </div>
  )
}
