export interface FormLayoutItemOption {
  value: string
  label: string
}

/** 人员/部门/用户组等引用类字段的数据来源 */
export type FormLayoutItemDataSource = 'all' | 'by_department' | 'by_group' | 'manual'

export interface FormLayoutItem {
  id: string
  /** 显示名称（如 名称、资产标签号） */
  label: string
  /** 数据类型或字段类型 key */
  type: string
  /** 分组 key: basic | config | org | audit */
  group: string
  /** 技术字段名（如 name, asset_tag），来自属性时必填 */
  technicalName?: string
  /** 是否必填，用于显示 名称* */
  required?: boolean
  /** 是否只读（审计信息组默认只读） */
  readOnly?: boolean
  /** 占位提示（输入框、下拉等） */
  placeholder?: string
  /** 下拉/单选/多选/级联的选项，编辑时可配置（手动维护时使用） */
  options?: FormLayoutItemOption[]
  /** 多行文本行数 */
  textareaRows?: number
  /** 唯一编码等：根据识别规则自动生成，不可手动输入 */
  autoGenerated?: boolean
  /** 人员/部门/用户组：数据来源（全部 / 按部门筛选 / 按用户组筛选 / 手动指定） */
  dataSource?: FormLayoutItemDataSource
  /** 按部门筛选时的部门 ID，或按用户组筛选时的用户组 ID */
  dataSourceFilter?: { departmentId?: string; groupId?: string }
  /** 人员/部门/用户组等引用类是否允许多选（默认单选） */
  multiple?: boolean
}

/** 表单分组定义（与字段分组方案一致） */
export const FORM_GROUP_SCHEMA = [
  { key: 'basic', title: '【基本信息】', subtitle: '必填字段组' },
  { key: 'config', title: '【技术配置】', subtitle: '可选字段组' },
  { key: 'org', title: '【组织归属】', subtitle: '管理字段组' },
  { key: 'audit', title: '【审计信息】', subtitle: '只读字段组' },
] as const

/** 系统/行业模板：预填分组与建议字段（technicalName 列表，按顺序） */
export interface FormTemplate {
  id: string
  name: string
  description: string
  groups: { groupKey: string; fieldTechnicalNames: string[]; required?: string[] }[]
}

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    id: 'blank',
    name: '从空白开始',
    description: '不预填任何字段，自行拖拽配置',
    groups: [],
  },
  {
    id: 'standard_ci',
    name: '标准 CI 模板',
    description: '适用于通用配置项，仅配置业务必需字段',
    groups: [
      { groupKey: 'basic', fieldTechnicalNames: ['name', 'operational_status', 'asset_tag'], required: ['name', 'operational_status'] },
      { groupKey: 'org', fieldTechnicalNames: ['company', 'department', 'owned_by'] },
      { groupKey: 'audit', fieldTechnicalNames: ['sys_created_on', 'sys_updated_on', 'sys_created_by'] },
    ],
  },
  {
    id: 'server',
    name: '服务器模板',
    description: '服务器类 CI：基本信息 + 技术配置 + 组织归属 + 审计',
    groups: [
      { groupKey: 'basic', fieldTechnicalNames: ['name', 'operational_status', 'asset_tag', 'install_status'], required: ['name', 'operational_status'] },
      { groupKey: 'config', fieldTechnicalNames: ['cpu_count', 'ram', 'disk_capacity'] },
      { groupKey: 'org', fieldTechnicalNames: ['company', 'department', 'owned_by', 'location'] },
      { groupKey: 'audit', fieldTechnicalNames: ['sys_created_on', 'sys_updated_on', 'sys_created_by'] },
    ],
  },
  {
    id: 'application',
    name: '应用模板',
    description: '应用类 CI：基本信息 + 版本/环境 + 组织归属 + 审计',
    groups: [
      { groupKey: 'basic', fieldTechnicalNames: ['name', 'operational_status', 'asset_tag'], required: ['name'] },
      { groupKey: 'config', fieldTechnicalNames: ['version', 'deploy_env'] },
      { groupKey: 'org', fieldTechnicalNames: ['company', 'department', 'owned_by', 'supported_by'] },
      { groupKey: 'audit', fieldTechnicalNames: ['sys_created_on', 'sys_updated_on', 'sys_created_by'] },
    ],
  },
]

/** 模板中可能用到的 technicalName 在无属性匹配时的显示名（如扩展属性未在属性表时） */
export const TEMPLATE_FIELD_LABELS: Record<string, string> = {
  cpu_count: 'CPU 核数',
  ram: '内存',
  disk_capacity: '磁盘容量',
  version: '版本号',
  deploy_env: '部署环境',
}

